### ISSUE TITLE
Icon is missing

### ISSUE THREAD

**Issue by ozky** [VioletDarkKitty/system-monitor#2]
You have added to desktop file icon but it's missing.
Also this is wrong place to install any icons.
`Icon=/usr/share/system-monitor/system-monitor.png`
Right would be this.
`Icon=/usr/share/icons/system-monitor/system-monitor.png`

**Comment by VioletDarkKitty** [comment]
Could you do a pull request for the path change please?

Also, I was going to use the same icon that gnome does but I think it's under copyright so I need to get in contact with the artist and ask to use it. Should be fixed soon.

**Comment by ozky** [comment]
Yeah seems to be good idea to use original icon.
I could do pull request but i have never done it in github so i have no idea how it works.
Also i am not developer myself so i use mainly github to report issues.

**Comment by VioletDarkKitty** [comment]
Actually, it looks like ubuntu based distros use the path I've used. What are you on? KDE?

The icons folder has theme things in it

**Comment by ozky** [comment]
I use Mageia 6 sta2 with lxqt as this your system-monitor is so much more better and up to date than qps.

**Comment by VioletDarkKitty** [comment]
Should there be a special case for other distros then? I'll have to take a look

**Comment by ozky** [comment]
Adwaita icon theme provides gnome-system-monitor icon by default,it's installed in Mageia by default.
`/usr/share/icons/Adwaita/16x16/apps/utilities-system-monitor.png`
Icon should not have any licence problems according to this.
https://commons.wikimedia.org/wiki/File:Gnome-utilities-system-monitor.svg

**Comment by ozky** [comment]
Thanks it works now. :D
